Add support for @grpc/grpc-js
improbable-eng/ts-protoc-gen pull request #236
Opened 2020-06-16 07:06 UTC by badsyntax

- Refs https://github.com/improbable-eng/ts-protoc-gen/issues/226, https://github.com/improbable-eng/ts-protoc-gen/pull/234

Add support for generating file that import `@grpc/grpc-js`. This does not change the default behaviour of the package, but instead introduce a new param that allows you to generate files that require `@grpc/grpc-js` instead of `grpc`.

## Changes

- Add new `mode` param, for example:

```sh
--ts_out=service=grpc-node,mode=grpc-js
```

- Add generated examples

## Verification

I've only tested it via the generated examples. It's very similar to `server=grpc-node` other than changing the import paths.

2020-07-03 03:05 UTC, laike9m commented
BTW, I tried installing the `grpc-node-mode` branch using

```
npm install badsyntax/ts-protoc-gen#grpc-node-mode
```

run it, and got this error:

```
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module '../lib/index'
```

It seems the `lib` directory does not exist in `ts-protoc-gen` directory under `node_modules`.

2020-07-03 06:56 UTC, badsyntax commented
The lib directory is only built on `prepublishOnly` (before the package is published to npm), so installing via git won't work, see:

https://github.com/improbable-eng/ts-protoc-gen/blob/3e58c65351d72cd7280c0cb16e8f7e758fb88e79/package.json#L15

2020-07-03 07:03 UTC, laike9m commented
Thanks for the quick response. Any suggestions on what I should do to make it work? Or should I stick with `sed` for now like https://github.com/badsyntax/grpc-js-types?

2020-07-03 07:05 UTC, avdeev commented
Quick fix:

```sh
sed -i -- 's/import \* as grpc from "grpc";/import \* as grpc from "@grpc\/grpc-js";/g' *
```

2020-07-03 07:06 UTC, badsyntax commented
if you want to continue using this package, then you're going to have to stick with sed. but as mentioned here https://github.com/grpc/grpc-node/pull/1380#issuecomment-653388835, I would suggest to try the new typescript generator offered by the author of grpc-js

2020-09-09 15:49 UTC, AndreyUtka commented
Hi @badsyntax, Any plans to merge this PR?

2020-09-09 18:33 UTC, badsyntax commented
I can't merge as I'm not the owner of this repo. Not sure why I haven't got a review yet :(

2020-09-09 21:00 UTC, AndreyUtka commented
@MarcusLongmuir Can you please help?

2020-09-09 21:29 UTC, MarcusLongmuir requested changes
Thanks for the contribution! Apologies for the long delay in waiting for a review. This had gone under the radar.

Only a few minor things 👍

2020-09-09 21:29 UTC, MarcusLongmuir commented on src/service/grpcnode.ts
> +export function generateGrpcNodeService(filename: string, descriptor: FileDescriptorProto, exportMap: ExportMap, modeParameter: string | undefined): CodeGeneratorResponse.File {
This function is only called from the `index.ts` file so the argument could either be an enum to make the mode explicit.

2020-09-09 21:29 UTC, MarcusLongmuir commented on src/index.ts
> +    if (service === "true") {
The `service` parameter should probably have more validation and helpful warnings, but this additional parameter makes that even clearer.

Can you add checks for the supported `service` and `mode` values and change this to throw exceptions if they're unrecognised to help users more quickly identify misconfigurations please?

2020-09-10 19:20 UTC, badsyntax commented
I've made those changes:


Running:

`protoc --plugin="protoc-gen-ts=${PROTOC_GEN_TS_PATH}" --plugin=protoc-gen-grpc=${PROTOC_GEN_GRPC_PATH} --js_out="import_style=commonjs,binary:${OUT_DIR}" --ts_out="service=grpc-nodde:${OUT_DIR}" --grpc_out="${OUT_DIR}" proto/examplecom/simple.proto`

Shows:

```sh
protoc-gen-ts error: Error: Unrecognised service parameter: grpc-nodde
    at getServiceParameter (/Users/richardwillis/Projects/badsyntax/ts-protoc-gen/lib/util.js:155:19)
    at Object.getParameterEnums (/Users/richardwillis/Projects/badsyntax/ts-protoc-gen/lib/util.js:173:18)
    at /Users/richardwillis/Projects/badsyntax/ts-protoc-gen/lib/index.js:19:25
    at Socket.<anonymous> (/Users/richardwillis/Projects/badsyntax/ts-protoc-gen/lib/util.js:74:9)
    at Socket.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

--ts_out: protoc-gen-ts: Plugin failed with status code 1.
```

Running:

`protoc --plugin="protoc-gen-ts=${PROTOC_GEN_TS_PATH}" --plugin=protoc-gen-grpc=${PROTOC_GEN_GRPC_PATH} --js_out="import_style=commonjs,binary:${OUT_DIR}" --ts_out="service=grpc-node,mode=grpc-jss:${OUT_DIR}" --grpc_out="${OUT_DIR}" proto/examplecom/simple.proto`

Shows

```sh
protoc --plugin="protoc-gen-ts=${PROTOC_GEN_TS_PATH}" --plugin=protoc-gen-grpc=${PROTOC_GEN_GRPC_PATH} --js_out="import_style=commonjs,binary:${OUT_DIR}" --ts_out="service=grpc-node,mode=grpc-jss:${OUT_DIR}" --grpc_out="${OUT_DIR}" proto/examplecom/simple.proto
protoc-gen-ts error: Error: Unrecognised mode parameter: grpc-jss
    at getModeParameter (/Users/richardwillis/Projects/badsyntax/ts-protoc-gen/lib/util.js:166:19)
    at Object.getParameterEnums (/Users/richardwillis/Projects/badsyntax/ts-protoc-gen/lib/util.js:174:15)
    at /Users/richardwillis/Projects/badsyntax/ts-protoc-gen/lib/index.js:19:25
    at Socket.<anonymous> (/Users/richardwillis/Projects/badsyntax/ts-protoc-gen/lib/util.js:74:9)
    at Socket.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

--ts_out: protoc-gen-ts: Plugin failed with status code 1.
```

2020-09-10 19:51 UTC, merged

2020-09-10 20:02 UTC, badsyntax commented
Awesome, thanks!

2020-09-10 21:21 UTC, avdeev commented
@badsyntax Thanks! Could you release it?

2020-09-10 21:22 UTC, AndreyUtka commented
thanks !

2020-09-10 21:28 UTC, MarcusLongmuir commented
Unfortunately the repo and org setup appears to make that quite difficult without another maintainer so I'll have to do it in the morning when others come online.

If you want to validate usage in the meantime there is now a published version on npm: https://www.npmjs.com/package/ts-protoc-gen/v/0.12.1-pre.6383416.

I'll comment on this PR when the release goes out.

2020-09-11 09:22 UTC, MarcusLongmuir commented
`0.13.0` is now out: https://www.npmjs.com/package/ts-protoc-gen/v/0.13.0

2020-09-11 19:19 UTC, badsyntax commented
Thanks for the release. I've tested the change [in my project](https://github.com/badsyntax/vscode-gradle/pull/690) and it lgtm 👍